const SONGS_ARE_LOADED = 'SONGS_ARE_LOADED';
const LOADING_SONGS = 'LOADING_SONGS';
const FETCH_POSTS = 'FETCH_POSTS';
const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'

export {
    SONGS_ARE_LOADED,
    LOADING_SONGS,
    FETCH_POSTS,
    FETCH_DATA_ERROR
}